### ISSUE TITLE
[BUG] Required fields at signup

### ISSUE THREAD

**Issue by samumatic** [Lippesola/lama-api#13]
When you initially log in to lama with your ID, you have to enter your data again.
However, these fields are only partly set to "required", where one would actually think that they are required, or not.

For example, fields that are currently required in order to continue:
- Date of birth
- POSTCODE

Fields that are not, for example:
- Name
- First name

The list should therefore be revised again.

**Comment by Mipronimo** [comment]
> When you initially log in to lama with your ID, you have to enter your data again.

This is fixed in bca69ec

**Comment by samumatic** [comment]
When you click the "Speichern" button with missing values, it just does nothing, not complaining what the user did wrong.

A check for every field, and a possible altert if not valid would be more helpful.

**Comment by Mipronimo** [comment]
Fixed it

**Comment by samumatic** [comment]
@Mipronimo at the moment, the required fields order goes like this:

1. Sign in with SoLa ID
2. Certain Fields are filled automatically
3. Try to save, error: "Beziehungsstatus" not filled
4. Filling "Beziehungsstatus"
5. Try to save, error: "Ort, Handynummer, Gemeinde, Straße und Hausnummer, Beruf" not filled
6. Filling the error marked missing Fields
7. Some seem not required

is this behavior intended?
