### ISSUE TITLE
[Question] third value in "Voraufbau" 

### ISSUE THREAD

**Issue by samumatic** [Lippesola/lama-api#17]
In step 3 of the registration process the field "Voraufbau" has an option to take the same value as the "Teens" value.
But this is no default, just another choice, but why make "two" choices for the same result? 
When it would be a default value, it would save the user a click, but it's questionable, if it is really necessary. 

![Screenshot_20230124-172820~2](https://user-images.githubusercontent.com/62831433/214351618-af3f3101-6367-4e47-9b83-fb486e7b18f9.png)

Tested on mobile.

**Comment by Mipronimo** [comment]
Fixed it. Thanks
